[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "Isaac Lab Extended Tasks"
description = "Extension containing configuration instances of different assets and sensors"
readme = "docs/README.md"
repository = "https://github.com/makolon/IsaacLabExtendedTasks"
category = "robotics"
keywords = ["kit", "robotics", "assets", "isaaclab"]

[dependencies]
"omni.isaac.lab" = {}

# Main python module this extension provides.
[[python.module]]
name = "omni.isaac.extended_tasks"